title: "Guan Wang"
author: "Guan Wang"
description: " "
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  
  - {file: "gwang_cv_092022.pdf",title: "CV"}
  - {title: "Dissertation"}
  - {file: "publications.md",title: "Publications"}
  - {title: "Working Projects"}
  - {file: "contactinfo.md",title: "Contact Info"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:gwang921@umd.edu"}
  
  - {title: Twitter, icon: twitter, url: "https://twitter.com/Guan_Wang921"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
